name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for your issue! Ill take a look soon'' first issue'
        pr-message: 'You.Are.A.Star.THANKUUUUUUUUUU'' first pr'
